### ISSUE TITLE
Dark theme

### ISSUE THREAD

**Issue by rakleed** [june07/NiM#122]
At night or in a dark room, it is very uncomfortable for the eyes to use your extension, because the bright white background hurts the eyes. A dark theme that is enabled when the OS also has a dark theme enabled would be a great solution. Optionally, you can add manual theme selection between Auto/Light/Dark.

**Comment by june07** [comment]
Please note that https://github.com/june07/nimv3 where dark mode has been implemented. That will be the next version of NiM as Google is killing Manifest v2 extensions.

Here's a screenshot from my own desktop showing dark mode:

![image](https://github.com/june07/NiM/assets/11353590/f206b213-bbd1-4709-b746-160ebebcb9c0)

**Comment by rakleed** [comment]
Do you plan to publish a preview version with Manifest V3 in CWS or will you just update the current version to MV3 after some time?

**Comment by june07** [comment]
It's been available in the Edge Add-Ons for some time, however I was delaying pushing it to Chrome Web Store until forced (by Google discoing V2), at which time it will replace the current version.

Here's the edge link:
https://microsoftedge.microsoft.com/addons/detail/nodejs-v8-inspector-ma/bhgmgiigndniabncaajbbeobkcfjkdod

I know the Edge Browser has functionality to install Chrome Web Store extensions, but I'm not sure if Chrome has similar functionality (i.e. you may have to use Edge)

**Comment by rakleed** [comment]
In Chrome, there is no way to install extensions from Edge Add-Ons.

Why don't you want to publish in CWS as a new NIMV3 extension as you did in Edge Add-Ons?

**Comment by june07** [comment]
![image](https://github.com/june07/NiM/assets/11353590/e4282791-fb0d-45d6-a8b7-04f58163e325)
