### ISSUE TITLE
Hostname is really IP address

### ISSUE THREAD

**Issue by georgecrawford** [june07/NiM#32]
You prompt for a hostname, but the [validation on the field](https://github.com/june07/Node.js-inspector-Manager-NiM-/blob/25777380ca275662cf08e8402f98f96cc0c2f496/popup.html#L176) only accepts an IP address or localhost. Is there a reason why you don't accept a hostname? I'm debugging a container which has a variable IP address, but always has the same hostname which I add to `/etc/hosts`. Hence the hostname always resolves to a local IP (198.x.x.x), and I'd imagine it would work for debugging. Chrome can happily accept the hostname in the chrome://inspect/#devices network targets configuration.

**Comment by june07** [comment]
Great point.  See https://github.com/june07/Node.js-inspector-Manager-NiM-/commit/91c68383769dc92169c7eea6e0e87672bbf91ae4

Also pushing change to Chrome Web Store now.

**Comment by june07** [comment]
https://github.com/june07/NiM/commit/024cb657c07d271452def3206c6cf350260cfc0e
