### ISSUE TITLE
Make keyboard short cut (cmd-I) configurable (or different?)

### ISSUE THREAD

**Issue by nilsjesper** [june07/NiM#36]
This might sound silly but it'd be great to make the keyboard shortcut to show the inspector configurable.  Currently cmd-i interferes with at anywhere in chrome one might use italics (gmail, google docs, the github markdown editor for that matter).  Either that or set it to a different default.

I suppose I could just fork this and make my own plugin with a different keyboard command but that seems like overkill!

**Comment by june07** [comment]
Please see https://github.com/june07/NiM/pull/31
And https://github.com/june07/NiM/issues/35.

**Comment by nilsjesper** [comment]
Closing as a dupe. Thanks for addressing it so quickly!
