### ISSUE TITLE
NiM should not bind Command+I by default

### ISSUE THREAD

**Issue by nickmccurdy** [june07/NiM#37]
`Command+I` is a common keyboard shortcut for italicizing text (including in Google Docs) or getting information in web applications. It would be great if NiM would leave this keyboard shortcut alone so it can be used in Chrome, or at least give the option to disable or change it.

![image](https://user-images.githubusercontent.com/927220/32348750-39420de2-bfeb-11e7-9b75-807976b32284.png)

**Comment by june07** [comment]
Nick,

Thanks for the feedback.  This was actually addressed recently:
https://github.com/june07/NiM/pull/31

It's actually very simple to change by clicking on the pop-up.  I will put up a post soon to demonstrate how.

**Comment by nickmccurdy** [comment]
Thanks for your help, I didn't even realize this was configurable. Apparently, the option to change the shortcut is hidden under `More` (so I didn't realize it was there) and it's in Chrome extensions keyboard settings, not the settings for the extension itself.

I appreciate this flexibility, though I personally think the default shortcut should be changed to something less common or removed by default with some sort of notification or notice in the settings panel about assigning a custom keyboard shortcut.

**Comment by nilsjesper** [comment]
I had no idea this was configurable either, especially since the notification disappears pretty quickly.  Good to know it can be changed but +1 on just swapping it to a less common default.

**Comment by june07** [comment]
Pushed update to Web Store.  "Alt+I" is now the default.
