### ISSUE TITLE
Chrome Store url broken

### ISSUE THREAD

**Issue by styts** [june07/NiM#39]
Url pointing to http://june07.com/nim is dead.

**Comment by giorgiobeggiora** [comment]
+1

**Comment by june07** [comment]
Please see https://twitter.com/june07t/status/940987864568946688

**Comment by june07** [comment]
Feel free to support.

**Comment by june07** [comment]
@giorgiobeggiora THANK YOU.  Your support on Twitter was fantastic.  A huge thanks!

See https://twitter.com/june07t/status/941560289228500992

And https://june07.com/nim is back!

**Comment by giorgiobeggiora** [comment]
you're welcome 👍  it's the least i can do for you that are improving the developers' life!
