### ISSUE TITLE
503 error after installing

### ISSUE THREAD

**Issue by nickmccurdy** [june07/NiM#40]
When installing NiM in a new Chrome Canary profile, http://june07.com/blog/nim-install opens in a new tab served by Heroku with a 503 "Application Error". The NiM icon still appears in my toolbar and the popup still displays properly, so I'm guessing it's just a server issue in your post installation site.

**Comment by june07** [comment]
Thanks for the heads up Nick!  I've been sick as a dog the past few days and my eyes have been away from the screen.  Looks like I've run up against the Heroku limits:

Free app running time quota exhausted

And yes, it shouldn't affect the apps performance as it's just a "thanks for installing" page.  But I will be looking into a fix asap.

**Comment by nickmccurdy** [comment]
Is it just a static web page? If so I'd recommend hosting it on GitHub Pages, it's free and you can even keep the source in this repository.

**Comment by june07** [comment]
Nick, it's actually a ghost blog installation.  I moved it over to my Digital Ocean stuff so we should be good now.  Thanks again for the heads up.

**Comment by nickmccurdy** [comment]
Oh ok great, just wanted to warn you about the installation UX. Thanks for fixing it. 😄
