### ISSUE TITLE
NiM doesnt open.

### ISSUE THREAD

**Issue by antonio-goncalves** [june07/NiM#41]
![screen shot 2017-12-28 at 10 17 25](https://user-images.githubusercontent.com/20188451/34407898-b3b0f374-ebb8-11e7-92f9-407523b3bcf4.png)

**Comment by june07** [comment]
Did you find a resolution?

**Comment by antonio-goncalves** [comment]
Yes I wasn't running node with the "--inspect" option

Thank You
