### ISSUE TITLE
if host is "localhost" i have error

### ISSUE THREAD

**Issue by imegamaximus** [june07/NiM#46]
if host is "localhost" i have error

![image](https://user-images.githubusercontent.com/37433887/39092320-fd725876-4613-11e8-9ca0-6837eceafef8.png)

fix: i change host to "127.0.0.1"
![image](https://user-images.githubusercontent.com/37433887/39092313-ea6006fc-4613-11e8-9d49-cc75bf1e0f64.png)

**Comment by june07** [comment]
What version is that?

**Comment by imegamaximus** [comment]
@june07  version 0.14.5 have problem
![image](https://user-images.githubusercontent.com/37433887/39157513-cd9c2c84-4763-11e8-92cf-a35191c3b5bd.png)

**Comment by june07** [comment]
Tried to duplicate on my end using the RU locale but it seems to work fine for me.  See http://recordit.co/JN8ryTUi1i.

**Comment by imegamaximus** [comment]
@june07 
![image](https://user-images.githubusercontent.com/37433887/39165266-4d911f26-478c-11e8-8302-33028318bb29.png)

**Comment by imegamaximus** [comment]
@june07 

```javascript
"chrome-devtools://devtools/bundled/inspector.html?experiments=true&v8only=true&ws=localhost:9229/31d30fc8-070a-43d2-a9ba-a41fb60c5483"
```

**Comment by june07** [comment]
What version of Node?

**Comment by june07** [comment]
As you can see here Node (v8.9.4) doesn't output "localhost" in the web socket url.  I will certainly add a fix for that asap.  But I am curious what version you are running so I can hunt down the Node.js code to confirm my suspicion.

![screenshot 16](https://user-images.githubusercontent.com/11353590/39201272-59d5142e-47a3-11e8-9617-d34632d12eb7.png)

**Comment by imegamaximus** [comment]
@june07

Node 9.11.1

**Comment by imegamaximus** [comment]
@june07 you cool, ths =)
