### ISSUE TITLE
Doesn't open tab

### ISSUE THREAD

**Issue by melnikaite** [june07/NiM#47]
Inspector tab doesn't open automatically after upgrading Chrome to 66.0.3359.117 64-bit
If I switch to manual and click Open DevTools it says either "TYPEERROR: CANNOT READ PROPERTY '0' OF NULL" or "OPENING TAB IN PROGRESS..." and nothing happened.

Workaround: open chrome://inspect/#devices and click Inspect link

OS X: 10.13.4
Chrome: 66.0.3359.117
NiM: 0.14.5

**Comment by june07** [comment]
I'm aware of this and a fix will be pushed hopefully sometime today.

**Comment by melnikaite** [comment]
Yes, it works
