### ISSUE TITLE
Chrome 67 inspector.html has huge side pane that can't be closed

### ISSUE THREAD

**Issue by JonDum** [june07/NiM#50]
<img width="1552" alt="screen shot 2018-06-10 at 4 55 01 pm" src="https://user-images.githubusercontent.com/191920/41207696-17fe201c-6ccf-11e8-97af-4700f01779fb.png">

Started happening in Chrome 67.

If you change url from `chrome-devtools://devtools/bundled/inspector.html` to `chrome-devtools://devtools/bundled/js_app.html` it goes away.

What is this thing? It's taking up valuable debugging real estate! 🦀

**Comment by june07** [comment]
I'm unable to test.tgis right at the moment, but it sounds like a question for the Chrome Dev team.

**Comment by june07** [comment]
Tested on Version 67.0.3396.87 (Official Build) (64-bit) and I can't reproduce the issue you are seeing.  Try the "toggle Screencast" button.  It's light blue in your screenshot and I've circled it in red.
![41207696-17fe201c-6ccf-11e8-97af-4700f01779fb](https://user-images.githubusercontent.com/11353590/41374817-11bd0394-6f09-11e8-8e2e-833a588c529b.png)

**Comment by JonDum** [comment]
Yep that was it. Wouldn't thought how that little guy got enabled. Sorry for wasting your time.

Thanks for the plugin btw, works great!
