### ISSUE TITLE
"Open DevTools" button just shows "[object object]"

### ISSUE THREAD

**Issue by RaphaelDDL** [june07/NiM#52]
Hi,

Maybe I'm doing something wrong, idk. I use es6 (babel), so my npm script is `nodemon --inspect src/Application.js --exec babel-node`. It does work, but I have the issue of the ws changing url always, so I installed NiM.

Unfortunately, leaving on auto does nothing. Leaving on manual and clicking on `Open DevTools` gives me the following:
![screen shot 2018-07-12 at 8 26 45 pm](https://user-images.githubusercontent.com/1087109/42664575-e9e2ea26-8611-11e8-88a5-6b965476a0af.png)

I'm getting the following when pressing Open DevTools:
![screen shot 2018-07-12 at 8 24 44 pm](https://user-images.githubusercontent.com/1087109/42664555-d7704320-8611-11e8-9813-4320090ca561.png)

I'm currently using Canary v69
Any ideas?
Thank you!

**Comment by june07** [comment]
You want to have 9229 as the port, not 8081.

**Comment by RaphaelDDL** [comment]
oh, OH. So it's the WS port the extension needs, not the node server one. 
Oh, all right. Dumb me. I did the change, now the DevTools open :) 

Thank you, sorry to bother!
