### ISSUE TITLE
Cannot open Developer Tools: "TYPEERROR: CANNOT READ PROPERTY '0' OF NULL"

### ISSUE THREAD

**Issue by jimbo1qaz** [june07/NiM#53]
Version 68.0.3440.106 (Official Build) Built on Ubuntu , running on Ubuntu 18.04 (64-bit)

Extension Version: 0.15.0

When I switch to Auto and press Enter, or switch to Manual and click "Open DevTools", I receive error TYPEERROR: CANNOT READ PROPERTY '0' OF NULL.

Host is `localhost` or `127.0.0.1`, port is `9229`.

**Comment by jimbo1qaz** [comment]
This happens when I'm running `--inspect-brk` with a Node v8.9.3 application and environment `ELECTRON_RUN_AS_NODE=true`, even though the URL is visible via <http://localhost:9229/json/list>. This does not occur when running the `node` v8.10.0 shell via the command line.

**Comment by june07** [comment]
Could you copy the output from http://localhost:9229/json and http://localhost:9229/json/list and paste it here.
