### ISSUE TITLE
Opening Tab in Progress

### ISSUE THREAD

**Issue by brucejo75** [june07/NiM#63]
### Environment
- NiM 1.3.0
- Chrome Version 70.0.3538.77 (Official Build) (64-bit)

### Repro:
1. click on NiM icon.
2. click on Open DevTools

**Result:** a little popup in red text that says: `OPENING TAB IN PROGRESS...`
Tried with options set to tab or window.

Maybe related to #47?

### Workaround
restart chrome 😞

**Comment by june07** [comment]
Bruce try uninstalling and reinstalling and let me know if that doesn't resolve the issue.

**Comment by brucejo75** [comment]
I was on 1.2.1 then I upgraded to 1.3.0 and the error still occurred.

So I tried this:
1. Remove NiM
2. Shutdown and restart Chrome
3. Install NiM.
4. Open a devTools tab (good), close it.
5. Re-open a devTools tab (good).
6. Change option to open a window.
7. I can open the window once but I get an error message on the 2nd try.
8. Switch back to tabbed and the error occurs with tabs now.

### Workaround
Set options to tabbed, shutdown chrome, restart chrome all works OK with tabs.
As soon as I set it to windows, trouble starts to happen, so I will leave it in tabbed.

**Comment by brucejo75** [comment]
oh well... that doesn't really work either.  I still get the `OPENING TAB PROGRESS...` popup

**Comment by june07** [comment]
Bruce, I haven't been able to duplicate the problem on my end, exactly, but I did find a spot in the code  that I think may be the cause of the problem your experiencing.  I've already written the code and will push it soon, hopefully next week sometime.

**Comment by brucejo75** [comment]
It seems to happen more often if I kill rebuild the process that is being debugged before I close the chrome inspector window.

**Comment by june07** [comment]
This should be resolved now.  Just dropped v2.0.0.  If not the case please re-open.  Thanks.
