### ISSUE TITLE
Why there are many clones on CWS?

### ISSUE THREAD

**Issue by eight04** [june07/NiM#65]
https://chrome.google.com/webstore/detail/nim-nodejs-v8-inspector-m/hcmhfccfbcjjhhhnlpolgcpcjgggkejd
https://chrome.google.com/webstore/detail/nodejs-inspector-manager/bnmjajghllhhhgiaeipaibfmnjnponhd
https://chrome.google.com/webstore/detail/nodejs-v8-inspector-manag/gnhhdgbaldcilmgcpfddgdbkhjohddkj

**Comment by june07** [comment]
Those are old versions.
