### ISSUE TITLE
Request less permissions

### ISSUE THREAD

**Issue by eight04** [june07/NiM#66]
I was rebuilding the Chrome profile and noticed that NiM was disabled because of new permissions:
![image](https://user-images.githubusercontent.com/1324510/48964012-57d0a280-efda-11e8-9e27-30d178cca903.png)

Not sure why the browser didn't complain about it before. IMO if you really want to save users' email, you should make it optional and allow users to opt-out.

Another question is about the host permission `*://*/*`. Why the extension has to request it for all URLs?

**Comment by june07** [comment]
There is a different version in the web store that you may like to use instead.  I wrote a blog post about it: http://blog.june07.com/foff/.

**Comment by eight04** [comment]
Telling people not to update doesn't really solve the problem. If you don't like the option, I suggest creating a fork without analytics/user tracking, then you can keep both versions on CWS and up-to-date.
