### ISSUE TITLE
NiM Icon in Chrome Menu disappears when clicked

### ISSUE THREAD

**Issue by flohil** [june07/NiM#68]
When I click on the NiM Icon in the chrome menu/toolbar (at the top of the browser window), the NiM Icon simply disappears from the menu bar. I then need to open Chrome Settings (right top corner) -> More Tools -> Extensions and it says that NiM Extensions may have been corrupted. I can then click on the "Repair" Button below the error message and the NiM icon will show up in the chrome menu bar again.

This is pretty frustrating because I cannot open the "main menu" of NiM. However, right-clicking on the NiM Icon works -> I can right-click the icon and from the context menu, choose "Option" to open NiM's option menu.

![image](https://user-images.githubusercontent.com/6840090/52710111-cfd1b780-2f8e-11e9-877f-f4a2e2ec2d78.png)
![image](https://user-images.githubusercontent.com/6840090/52710136-dd873d00-2f8e-11e9-9d0b-6c6bd6dd50cd.png)

I am using Chrome Version 72.0.3626.81 (Official Build) (64-bit) on an Ubuntu 16.04 machine.
The NiM Version is 2.0.0.

**Comment by june07** [comment]
See https://github.com/june07/NiM/issues/34.  Same issue I believe.  I haven't been able to track down why this is happening!?  I share your frustrations.

**Comment by alex-borkun** [comment]
Kubuntu 18.04:
NiM does not not work in Chrome, but works in Chromium as it was mentioned in a #34 issue.

**Comment by gtarsia** [comment]
It works for me now :tada:  
Chrome extension v2.0.2

**Comment by june07** [comment]
Indeed, you are the man!  If you're ever in the Bay Area, drinks on me.  Will update the readme soon to include credits to your favor for the fix.  Cheers!

**Comment by gtarsia** [comment]
@june07 thanks man, will have it mind if I ever go there.
