### ISSUE TITLE
Reason for new permissions

### ISSUE THREAD

**Issue by superclarkk** [june07/NIM#7]
Thanks for your work on this extension. It's made things a lot easier.

Could you explain why the permission requirements of the extension have changed recently? The latest change will reveal the user's email address. It would be a good idea to explain why each permission is necessary on the extension's description page.

**Comment by june07** [comment]
Superclarkk,

Thank you for your feedback.  Also for your suggestion to add an explanation to the description page.  I've updated the Chrome Web Store's description.

The only permission that was changed was "Know your email address" and I've explained other places why I made the change.  In short, it was to better understand my user base.  Here is the beginning of a blog post I've written and a thread on Reddit which may give you more insight: 

http://june07.com/foff
https://www.reddit.com/r/node/comments/5t8psv/node_inspector_manager_is_great_but_the_new/

**Comment by superclarkk** [comment]
Thanks for your reply, @june07. Sorry to hear that you've had some undeserved negative feedback from other users. Great job on clarifying the permissions on the description page, which will make it especially easier for new users to understand.
