### ISSUE TITLE
Setting to have inspector window maximized

### ISSUE THREAD

**Issue by thegirlprince** [june07/NiM#70]
Currently the inspector window opens with rather awkward dimensions on my laptop. The chrome.windows API allows setting the window to maximized (`https://developers.chrome.com/extensions/windows#method-create`) which would be great for my small laptop screen. Any chance you could add this? 

Being able to set the width and height if not maximized would be perfection :)

This is a super helpful extension btw, thanks.

**Comment by june07** [comment]
Thanks so much for the nice feedback.  I will certainly look more into the windowing.

**Comment by june07** [comment]
Just pushed 2.2.0 to the [Web Store](https://june07.com/nim).  Please give it a try and let me know how it works out for you.

**Comment by thegirlprince** [comment]
Fantastic! Thanks so much for adding that so quickly.
