### ISSUE TITLE
Network tab

### ISSUE THREAD

**Issue by Revadike** [june07/NiM#71]
There are no requests logging in the network tab. How do I fix this?
In my app I use node-request.

**Comment by june07** [comment]
I'm not sure your issue is specific to NiM.  It sounds more like a possible DevTools issue.  Can you provide screen shots/gif explaining the problem more...

**Comment by Revadike** [comment]
Not much to screenshot. It's just an empty network tab.

**Comment by june07** [comment]
https://blog.june07.com/devtoolscompat/

Just wrote this specifically in response to this issue.  I assume you are meaning that the Network tab is missing in which case this is likely the reason.  Changing the devtoolscompat setting in NiM should resolve things.

![image](https://user-images.githubusercontent.com/11353590/62014021-703c2280-b150-11e9-8adc-451968fad2aa.png)

vs

![image](https://user-images.githubusercontent.com/11353590/62014040-93ff6880-b150-11e9-99c4-bd651c7279db.png)

**Comment by Revadike** [comment]
![image](https://user-images.githubusercontent.com/4411977/62085678-715a7600-b25c-11e9-8128-d0165d528c2f.png)
Here, screenshot at last. Like I said, nothing to see here. In the node.js app that I am inspecting, http web requests are made via `node-request`. Yet, they do not show in the network tab. This is my problem.

**Comment by june07** [comment]
This issue is not NiM specific and has to do with the way DevTools interacts (or not in this case) with the Node debugger.  I don't think there's been movement on making the network telemetry available from Node via the debugger protocol.  See the following for more background...

https://github.com/nwjs/nw.js/issues/5341

**Comment by Revadike** [comment]
Too bad... the network monitor is by far the best thing about chrome dev tools :(

Please notify me here, if anyone reading this knows about any progress about this particular issue.
