### ISSUE TITLE
extension not saves auto/handle tumbler and not saves inspector-settings

### ISSUE THREAD

**Issue by ibyteyou** [june07/NiM#78]
NiM extension is beautiful, but after a year of rest, I launched it again on a new project and discovered two problems.
- extension not saves auto/handler tubler (my tumbler even a little buggy and glitch, i can record gif, seem to be low-fps gpu)
- chrome inspector not saves console options

MacOs 10.14.6 Mojave, Chrome 80.0.3987.132

![Снимок экрана 2020-03-10 в 11 29 57](https://user-images.githubusercontent.com/16253399/76289921-ab482c00-62c3-11ea-88f1-01ba3ecc8530.jpeg)
![Снимок экрана 2020-03-10 в 11 25 43](https://user-images.githubusercontent.com/16253399/76289927-adaa8600-62c3-11ea-8b86-18431cf4530d.jpeg)

**Comment by june07** [comment]
Thank you.  I will look further into this.

**Comment by june07** [comment]
Just tried to duplicate the issue on Windows and haven't been able to.  I will try on my MacBook as well...

Regarding the 2nd issue "chrome inspector not saves console options", that is likely an issue with that version of DevTools specifically and not NiM.  Might want to try changing DevTools versions.  These blog posts may help [https://blog.june07.com/nim-custom-devtools-url/](https://blog.june07.com/nim-custom-devtools-url/), [https://blog.june07.com/devtoolscompat/](https://blog.june07.com/devtoolscompat/).

**Comment by june07** [comment]
Thank you for your patience.  I was just able to duplicate the issue on my macbook!  A temporary workaround would be to go to your NiM settings and save them after changing from auto to manual or vice versa.  Please give the workaround a try and let me know if that helps...

**Comment by june07** [comment]
Seems to be a race condition between the switchHandler and the model update.  Still investigating a fix.

**Comment by patriciussanctus** [comment]
- open chrome
- change auto -> manual
- close chrome
- nim again saves "auto"

I do not know how to save the settings manually //

**Comment by june07** [comment]
![githubIssue78](https://user-images.githubusercontent.com/11353590/76826148-e91fe580-67d8-11ea-8f5e-8fb36ab9fbb9.gif)

**Comment by patriciussanctus** [comment]
oh so sorry, thanks, it's works

**Comment by june07** [comment]
Glad the fix worked for you.  Just a heads up.  Considering the recent times as well as the very long delays with the Chrome Webstore (although the NiM project has been fortunate not to have had any issues), I am going to delay any updates to the Chrome Webstore until further notice.

**Comment by june07** [comment]
Thanks for your patience on this one.  Fix has been pushed here https://github.com/june07/NiM/releases/tag/v2.4.2.  Will be pushed to both Google/Microsoft stores shortly.
