### ISSUE TITLE
Not working in chrome 83

### ISSUE THREAD

**Issue by pichuser** [june07/NiM#80]
Today I update my chrome to 83. And now this extension is broken... After write node --inspect --inspect-brk - I get many, very many tabs in chrome... New tab is opening every half second until stop terminal. The same behavior in canary (version 85)

**Comment by june07** [comment]
On top of this.  It appears to be an issue of Node still spitting our non agnostic debugging URLS.  I've actually implemented and pushed a fix to GitHub.  I will shortly push to the Chrome Web Store however there's no telling how long it will take for that to go thru.

**Comment by june07** [comment]
For those so inclined who would rather not wait I've pushed the file here as well:
https://github.com/june07/NiM/releases/tag/v2.4.0

**Comment by june07** [comment]
![image](https://user-images.githubusercontent.com/11353590/82613512-4be78180-9b7a-11ea-8310-85bc36bbe5d5.png)

**Comment by june07** [comment]
edge: https://microsoftedge.microsoft.com/addons/detail/injfmegnapmoakbmnmnecjabigpdjeme
chrome: https://chrome.google.com/webstore/detail/nodejs-v8-inspector-manag/gnhhdgbaldcilmgcpfddgdbkhjohddkj

So I published the update to both Microsoft and Google.  In the event Google in fact takes 

> several weeks

I would suggest trying [Microsoft Edge](https://blog.june07.com/squash-node-js-bugs-with-devtools-on-edge/) as I've found things go through the pipeline much faster with them.

**Comment by pichuser** [comment]
> For those so inclined who would rather not wait I've pushed the file here as well:
> https://github.com/june07/NiM/releases/tag/v2.4.0

Thank you so much! Increadible! Perfect!

**Comment by june07** [comment]
WOW, I take it back!
https://chrome.google.com/webstore/detail/nodejs-v8-inspector-manag/gnhhdgbaldcilmgcpfddgdbkhjohddkj

Kudos @dotproto and team for the swift approval!
