### ISSUE TITLE
Getting error WebSocket disconnected

### ISSUE THREAD

**Issue by farzadmf** [june07/NiM#83]
Hi,

I'm getting an error on startup; this is what I'm doing.

I configure the host to be "auto" in NiM:
![image](https://user-images.githubusercontent.com/5768792/85658171-f0c91300-b680-11ea-8790-d20ee6c5405a.png)

I create a simple `main.js` file, and then I run it using `node --inspect-brk main.js`. NiM detects the URL and opens, but I get the following error:
![image](https://user-images.githubusercontent.com/5768792/85658312-1c4bfd80-b681-11ea-9dde-e09b7e590f54.png)

OS & Versions:
OS: Manjaro Linux
Node: v14.4.0
NiM: 2.4.2 (as seen by the first screenshot)

Thank you

**Comment by june07** [comment]
Can you provide a screenshot of the DevTools window?  What is the DevTools URL?  Also possible to share the main.js file you are running... have you tried other files?

**Comment by farzadmf** [comment]
@june07 thank you for your answer, I'm not currently at my Linux machine, but I just tried on my Windows machine, and this is what I get:
![image](https://user-images.githubusercontent.com/5768792/85734158-cc922400-b6ca-11ea-80b3-4a1726da6998.png)

OS: Windows 10 (Version 2004 - OS Build 19041.329)
Node: v14.4.0
NiM: 2.4.2

My `main.js` only contains 2 lines (maybe that's why?)
```javascript
const hello = 'MY NAME';
console.warn('HELLO', hello);
```

And this is my terminal output:
```
Debugger listening on ws://127.0.0.1:9229/8715fbe1-5e97-4f3f-add7-30b7a137789c
For help, see: https://nodejs.org/en/docs/inspector
Debugger attached.
```

**Comment by june07** [comment]
See https://blog.june07.com/chromium-bug-900945/...

**Comment by farzadmf** [comment]
> See https://blog.june07.com/chromium-bug-900945/...

Wow, OK, that's interesting, given that the issue was opened in 2018, I don't think I should get my hopes up as to when the issue will be fixed :)

I don't have access to my Linux machine for the moment, but do you think it's the same issue affecting that?

**Comment by june07** [comment]
Never know with Google... sorta like a black box 😂.  Although, thankfully
in the case of NiM and the team involved, they have been speedy in
processing updates through the web store.

In terms of the Linux side of things, I wouldn't doubt if it was the same
issue but you can easily test by trying the aforementioned fix.

**Comment by farzadmf** [comment]
> they have been speedy in processing updates through the web store.

Good to know 🙂

> you can easily test by trying the aforementioned fix.

Sure, I'll give it a try and update this

**Comment by farzadmf** [comment]
Hey @june07, an update on my side for my Linux machine:

When I tried again now, I'm seeing the same message as what we talked about on Windows, so I think it's because of the same reason

**Comment by june07** [comment]
@farzadmf Thanks for the update.  I'll leave this issue open for others to find easier.  It would be nice to see a n upstream fix soon.

**Comment by june07** [comment]
See https://github.com/june07/nimv3 for updates as the project was upgraded to Manifest Version 3 due to Google's change.
