### ISSUE TITLE
Feature Request: Focus window only when debugger is paused

### ISSUE THREAD

**Issue by ceremcem** [june07/NiM#93]
The "Make Window Focused." option does not fit my workflow, so I disable it. However, it is useful to be notified when debugger pauses (at a breakpoint or when an exception is caught). 

It would be helpful to have a "Make Window Focused On Debugger Pause" option.

**Comment by june07** [comment]
A bit more testing on this code is needed but should have a working solutions soon.

**Comment by june07** [comment]
@ceremcem Please give the newest release a try.

![issue93](https://user-images.githubusercontent.com/11353590/95786630-d4330400-0c8c-11eb-93e3-300d1bbedf05.gif)

Also introduced a new image rotate utility.
![image](https://user-images.githubusercontent.com/11353590/95782389-a8ac1b80-0c84-11eb-9d48-1a86d37aa27e.png)

**Comment by june07** [comment]
https://github.com/june07/NiM/releases/tag/v2.7.0

**Comment by ceremcem** [comment]
Hi, 

I followed [this blog post](https://www.mattcutts.com/blog/how-to-install-a-chrome-extension-from-github/) and updated NiM manually: 

> download the extension as a .zip by looking for the “Download ZIP” button on the right-hand side of the project page on GitHub. Now extract/unzip the code somewhere. Then in Chrome go to Menu (the three lines)->More tools->Extensions. Click the “Developer mode” checkbox and then click the button labeled “Load unpacked extension…”.

> Now navigate in the resulting file dialog box until you are in the directory with a manifest.json file. For me, it was in the twlinkfy-master/ext directory. And that’s it! 

However, it didn't work as intended with the following settings: 

![image](https://user-images.githubusercontent.com/6639874/95811545-31c26180-0d1c-11eb-9778-9129355006f4.png)

# How it behaves 

1. When my NodeJS process restarted, it opens in a new, panel style window and gains focus immediately. (like the prev. version)
2. When the debugger paused, it doesn't gain focus. 

# Extra odd behavior 

Debugger attaches the process multiple times: 

```
...(my application's console.log)...
Debugger attached.
Debugger attached.
Debugger attached.
```

# System Information 

```
Chromium Version 83.0.4103.116 (Developer Build) built on Debian 10.4, running on Debian bullseye/sid (64-bit)
```

**Comment by june07** [comment]
Didn't consider the windows mode!  Just updated the code and added support for windowed mode.

https://github.com/june07/NiM/releases/tag/v2.7.1

Regarding the console messages, you will see one additional attach message due to NiM attaching in addition to DevTools.

Also you should be able to simply drag the zip file to your browser and install it that way.  Let me know how that works.

**Comment by ceremcem** [comment]
Short feedback: Nope, it still behaves the same. 

Also note that the behavior was the same on the previous version when I configured to "Open in tab" and not in new window. (So the problem shouldn't be related with that)

> Also you should be able to simply drag the zip file to your browser and install it that way.

Didn't work for me. Maybe it's because Chromium and not Chrome.

**Comment by june07** [comment]
FYI, confirmed different behavior on Linux today on my end.  My primary development environment is on Windows.

**Comment by june07** [comment]
See https://github.com/june07/nimv3 for updates as the project was upgraded to Manifest Version 3 due to Google's change.
