### ISSUE TITLE
NiM keyboard shortcut issue

### ISSUE THREAD

**Issue by delfuego** [june07/NiM#97]
I am getting a weird macOS (11.3.1) system notification when I try to use the NiM keyboard shortcut, option-I — see the attached screenshot, it's just Chrome telling me that NiM owns the shortcut, but nothing *happens*. (In other words, I type the shortcut and get the notification telling me NiM owns it, but DevTools doesn't open.)

Any thoughts?

I'm running Chrome 90.0.4430.93 (Official Build) (x86_64), NiM 2.8.0, and macOS 11.3.1 (20E241). 

<img width="364" alt="Screen Shot 2021-05-06 at 11 06 13 AM" src="https://user-images.githubusercontent.com/550511/117321616-494d6d00-ae5b-11eb-86bd-6c6279c54313.png">

**Comment by june07** [comment]
Thank you for the input.  I will try to give this a look over the weekend.

**Comment by june07** [comment]
So far I'm unable to duplicate the issue on my end:

chrome: Version 90.0.4430.93 (Official Build) (x86_64)
NiM: 2.8.0
macOS: 10.15.7

I've attached a screen share below.  Is NiM set to manual mode?

https://user-images.githubusercontent.com/11353590/117556193-089c5200-b01b-11eb-9524-72b5d2c59bbb.mov

**Comment by delfuego** [comment]
Thanks for looking into this! Here's a screen recording of what happens at my end — you'll see me enable the shortcut, and then every time I press it, I get the macOS notification "NiM owns the (⌥I) shortcut.", without the Dev Tools window opening.

https://www.dropbox.com/s/cbar0fc93c3msg5/NiM%20screen%20recording.mov?dl=0

I'm not sure what you mean by asking if NiM is set to manual mode — I don't know what that mode is. You'll see at the end of the screen recording, though, my full NiM extension options, if that's helpful.

**Comment by june07** [comment]
When you click on the NiM icon (upper right corner of the screen where the extension icon is next to the puzzle piece) the popup will allow you to choose manual/auto as well as change the port that should be set to match that which the inspector is listening on.

Are you sure that port matches whatever port you have the node debugger set to listen?  If it's the default 9229 can you open the debugger url manually by going to a url similar to...

devtools://devtools/bundled/inspector.html?experiments=true&v8only=true&ws=localhost:9229/5e9fc097-e1e4-4761-b411-ee49fe702a10

where "9229" is your port and "5e9fc097-e1e4-4761-b411-ee49fe702a10" is what is returned from node when you run with the --inspect flag set.

Alternately you could just telnet to the port and see if you can connect that way.

**Comment by delfuego** [comment]
Ah, I've never seen that dialog! I'm set to Auto, the port is correct. And note that NiM definitely launches automatically when I start my Node app and the debug port comes alive... so it's not that NiM isn't working. It's just that the keyboard shortcut is bringing up that macOS notification rather than bringing up the Dev Tools window!

**Comment by june07** [comment]
Try to change the "make window focused" option to on...

**Comment by june07** [comment]
Want to circle back around to this... were you able to try the last suggestion?
