### ISSUE TITLE
[BUG] DevTools failed to load SourceMap: Could not parse content Unexpected end of JSON input

### ISSUE THREAD

**Issue by MaxmaxmaximusAWS** [june07/NiM#98]
Windows 10

![image](https://user-images.githubusercontent.com/69426460/119591391-2ae5ec00-bddf-11eb-8652-b9312f763351.png)

![image](https://user-images.githubusercontent.com/69426460/119591435-418c4300-bddf-11eb-9280-4a073a63a0e1.png)

But chrome://inspect works correctly

**Comment by june07** [comment]
https://blog.june07.com/devtoolscompat/

See if that helps...
